server:
  port: 8090


spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

    jedis:
      pool:
        max-active: 20 # 连接池最大连接限制
        max-wait: -1 # 连接池最大阻塞等待时间（使用负数表示没有限制）
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 0 # 连接池最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）





